create database zilo_ecommerce

use zilo_ecommerce

CREATE TABLE products_clean(
    product_id VARCHAR(20) PRIMARY KEY,
    product_name VARCHAR(255),
    brand VARCHAR(255),
    category VARCHAR(255),
    price_mrp DECIMAL(10,2),
    price_sale DECIMAL(10,2),
    discount_pct DECIMAL(5,2),
    product_url VARCHAR(255),
    image_url VARCHAR(255),
    availability_note VARCHAR(255),
    pincodes_available VARCHAR(255),
    scrape_date DATE
);

CREATE TABLE orders_clean (
    order_id VARCHAR(20) PRIMARY KEY,
    order_ts DATETIME,
    product_id VARCHAR(20),
    quantity INT,
    unit_price DECIMAL(10 , 2 ),
    order_value DECIMAL(10 , 2 ),
    pincode INT,
    delivery_hours DECIMAL(5 , 2 ),
    on_time TINYINT,
    is_returned TINYINT,
    order_status VARCHAR(50),
    order_date DATE,
    order_hour INT,
    order_dow VARCHAR(15)
);


select * from products_clean
select * from orders_clean 



-- 1. What is the total revenue generated by each product category?
SELECT 
    p.category, 
    SUM(o.quantity * o.unit_price) AS total_revenue
FROM 
    orders_clean o
JOIN 
    products_clean p ON o.product_id = p.product_id
GROUP BY 
    p.category
ORDER BY 
    total_revenue DESC;

-- 2. What is the average order value (AOV)?
SELECT 
    ROUND(SUM(o.quantity * o.unit_price) / COUNT(DISTINCT o.order_id),2) AS AOV
FROM
    orders_clean o
      
-- 3. Which are the top 5 best-selling products by revenue?
SELECT 
    p.product_name, SUM(o.quantity * o.unit_price) AS revenue
FROM
    orders_clean o
        JOIN
    products_clean p ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY revenue DESC
LIMIT 5;


-- 4. What is the monthly revenue trend?
SELECT 
    DATE_FORMAT(o.order_date, '%Y-%m') AS month,
    SUM(o.quantity *o.unit_price) AS monthly_revenue
FROM
    orders_clean o
GROUP BY month
ORDER BY month;


-- 5. Which brands generate the most revenue?
SELECT 
    p.brand, SUM(o.quantity * o.unit_price) AS revenue
FROM
    orders_clean o
        JOIN
    products_clean p ON o.product_id = p.product_id
GROUP BY p.brand
ORDER BY revenue DESC;

-- How would you find the top 10 selling products in Mumbai from our orders table?
SELECT 
    p.product_name, SUM(o.quantity * o.unit_price) AS Revenue
FROM
    products_clean p
        JOIN
    orders_clean o USING (product_id)
GROUP BY product_name
ORDER BY Revenue
LIMIT 10;